#当前服务器端口
server:
  port: 8001

#注册中心配置
eureka:
  client:
    serviceUrl:
      defaultZone: http://register-center:8761/eureka/
  instance:
    prefer-ip-address: true

#mybatis配置
mybatis:
  #mybatis自身的一些配置，例如基本类型的别名
  config-location: classpath:mybatis/mybatis-config.xml
  #指定mapper文件夹的位置
  mapper-locations: classpath:mybatis/mapper/*.xml

spring:
  cache:
    type: REDIS
  #数据库配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: ENC(tfZChs+qZ0jZCHFQCHSYyu+0AxNlOAoI)
    url: jdbc:mysql://180.76.96.9:3306/micro-service?useUnicode=true&characterEncoding=utf-8
    username: ENC(rZdiSrG8T4hpU1Lyx242Fw==)
  
  #redis配置
  redis:
    #Redis数据库索引（默认为0）
    database: '0'
    #Redis服务器地址
    host: 180.76.96.9
    #Redis服务器连接端口
    port: 6379
    #连接超时时间（毫秒）
    timeout: 5000
    jedis:
      pool:
        #连接池最大连接数（使用负值表示没有限制）
        max-active: 50
        #连接池中的最大空闲连接
        max-idle: 20
        #连接池中的最小空闲连接
        min-idle: 2
        #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 3000